imports:
  - {resource: Backend/DashboardWidgets.yaml}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Weather2\:
    resource: '../Classes/*'

  # Will be called by GeneralUtility in AjaxRoutes
  JWeiland\Weather2\Ajax\DeutscherWetterdienstWarnCellSearch:
    public: true

  # Called by makeInstance in TYPO3's PluginPreview
  JWeiland\Weather2\Backend\Preview\Weather2PluginPreview:
    public: true

  # Called by makeInstance from FlexForm
  JWeiland\Weather2\UserFunc\FlexFormUserFunc:
    public: true

  JWeiland\Weather2\Service\WeatherServiceInterface:
    class: JWeiland\Weather2\Service\OpenWeatherService

